[EKA-7] Encapsulate the patient object inside a response object for patient discovery.
ProjectEKA/health-information-provider-library pull request #1
Opened 2019-12-31 14:29 UTC by chethandeshpande

Fixed the package names
Changed the contract to have patient object in discovery response instead of returning patient directly.
Moved request and response objects to respective folders.

2020-01-01 14:03 UTC, ganesanarun requested changes

2020-01-01 14:03 UTC, ganesanarun commented on health-information-provider-library/Patient/models/AuthenticationType.cs
> -        Direct, Mediated
old files also getting pushed, I guess.

2020-01-01 14:03 UTC, ganesanarun commented on health-information-provider-library/Patient/ILink.cs
>          Task<Tuple<PatientLinkReferenceResponse, Error>> LinkPatients(PatientLinkReferenceRequest request);
```suggestion
        Task<Tuple<PatientLinkReferenceResponse, Error>> LinkPatients(PatientLinkReferenceRequest request);
        
```

2020-01-01 14:03 UTC, ganesanarun commented on health-information-provider-library/Patient/Models/Gender.cs
> +        Male,
From HDCM, we are supposed to sent M/F/O.

2020-01-01 14:03 UTC, ganesanarun commented on health-information-provider-library/Patient/Models/IdentifierType.cs
> +        Mr,
```suggestion
        MR,
```

2020-01-02 09:39 UTC, chethandeshpande commented on health-information-provider-library/Patient/Models/IdentifierType.cs
> +        Mr,
According to naming conventions of Enum, it should be named in PascalCase. Shouldn't we be using that in our contract as well?

2020-01-03 11:59 UTC, ganesanarun approved these changes

2020-01-03 12:11 UTC, merged